#!name=Apple WLOC 定位修改
#!desc=修改 Apple 网络定位返回坐标 | 快捷指令(推荐): 设置地理位置 https://www.icloud.com/shortcuts/b326f991cc6a44deb5c408ecb6ea60f6 清理恢复位置 https://www.icloud.com/shortcuts/0b1b71c9ac5a4be39db5135c2381825d | 选点页面: https://wloc.gmw.cc.cd/
#!author=Yu9191 Rewrite
#!homepage=https://github.com/chiron09/wloc

[rewrite_local]
^https?:\/\/gs-loc(-cn)?\.apple\.com\/clls\/wloc url script-response-body https://raw.githubusercontent.com/chiron09/wloc/refs/heads/main/dist/wloc.js
^https?:\/\/gs-loc(-cn)?\.apple\.com\/wloc-settings\/save url script-echo-response https://raw.githubusercontent.com/chiron09/wloc/refs/heads/main/dist/wloc-settings.js

[mitm]
hostname = gs-loc.apple.com, gs-loc-cn.apple.com
